/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Signer, utils } from "ethers";
import type { Provider } from "@ethersproject/providers";
import type { Fee, FeeInterface } from "../../../contracts/abstract/Fee";

const _abi = [
  {
    inputs: [
      {
        internalType: "address",
        name: "token",
        type: "address",
      },
      {
        internalType: "uint256",
        name: "amount",
        type: "uint256",
      },
    ],
    name: "withdraw",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
];

export class Fee__factory {
  static readonly abi = _abi;
  static createInterface(): FeeInterface {
    return new utils.Interface(_abi) as FeeInterface;
  }
  static connect(address: string, signerOrProvider: Signer | Provider): Fee {
    return new Contract(address, _abi, signerOrProvider) as Fee;
  }
}
